name: AutoClearLagg
description: Recoded & improved auto clear lagg plugin

main: twisted\autoclearlagg\AutoClearLagg
version: 3.2.0
api: 4.0.0

author: [Twisted, Blackjack200]
website: https://github.com/TwistedAsylumMC/AutoClearLagg
